/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nic;

import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import javafx.stage.Screen;
import static nic.Nic.cn;
import static nic.loginScreen.admin_id;
import static nic.modify.modifyIs;
import static nic.modify.sid;
import static nic.modify.*;
/**
 *
 * @author priyansh singh
 */

public class entryForm extends javax.swing.JFrame {
    public ArrayList<ArrayList<String>> cy = new ArrayList<ArrayList<String>>();
    public ResultSet getData;
    public String pkName;
    public String pkdob;
    public String pklast;
    /**
     * Creates new form entryForm
     */
    public entryForm() {
        
        this.doi = null;
        for(int i = 0; i < 29;i++){
            cy.add(new ArrayList<>());
        }
        System.out.println("hiiiiii");
        initComponents();
        if(modifyIs == true){
            System.out.println("Value " + sid);
            setValue();
        }
        Dimension wd = Toolkit.getDefaultToolkit().getScreenSize();
         jScrollPane1.setSize(wd);
        this.setSize(wd);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mygroup1 = new javax.swing.ButtonGroup();
        mygroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        sexM = new javax.swing.JRadioButton();
        sexF = new javax.swing.JRadioButton();
        firstNamehindi = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        DOI = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        address3 = new javax.swing.JTextField();
        district = new javax.swing.JTextField();
        pincode = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        title = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        lastNamehindi = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        numberoflivessaved = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        bankCode = new javax.swing.JTextField();
        recommendingAuthorityothers = new javax.swing.JTextField();
        posthumousY = new javax.swing.JRadioButton();
        posthumousN = new javax.swing.JRadioButton();
        state = new javax.swing.JComboBox<>();
        earlierAwarded = new javax.swing.JComboBox<>();
        jointDeed = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        citation = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        save = new javax.swing.JButton();
        awardAppliedfor = new javax.swing.JComboBox<>();
        recommendingAuthority = new javax.swing.JComboBox<>();
        city = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1300, 1300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 1355));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 1355));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("First Name :  *");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Recommending Authority others :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 51));
        jLabel3.setText("(DD/MM/YYYY)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("First Name : (Hindi)  *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Title :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("JEEVAN RAKSHA PADAK SERIES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Sex :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Year :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Recommending Authority :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Date of Incident :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("(DD/MM//YYYY");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Date of Birth :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 51));
        jLabel13.setText("30th Sept 2018)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setText("between 1st Oct 2016 to");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Address 1 :  *");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Address 3  : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Last Name :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Award Applied For :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Lives Saved :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Joint Deed :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Last Name : (Hindi)");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Earlier Awarded :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Pincode :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Phone/Mobile no. :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Posthumous :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("District :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Number of ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Address 2 :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Age :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("State :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Bank/Branch Code :");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("City :");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, 20));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setText("PERSONAL PROFILE");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        sexM.setBackground(new java.awt.Color(255, 255, 255));
        mygroup1.add(sexM);
        sexM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sexM.setText("Male");
        sexM.setFocusable(false);
        sexM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexMActionPerformed(evt);
            }
        });
        jPanel1.add(sexM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        sexF.setBackground(new java.awt.Color(255, 255, 255));
        mygroup1.add(sexF);
        sexF.setText("Female");
        sexF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sexF.setFocusable(false);
        jPanel1.add(sexF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        firstNamehindi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNamehindiActionPerformed(evt);
            }
        });
        jPanel1.add(firstNamehindi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 260, -1));

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 260, -1));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        jPanel1.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 260, -1));

        DOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOIActionPerformed(evt);
            }
        });
        jPanel1.add(DOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 260, -1));

        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        jPanel1.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 260, -1));

        address3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address3ActionPerformed(evt);
            }
        });
        jPanel1.add(address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 260, -1));

        district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtActionPerformed(evt);
            }
        });
        jPanel1.add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 260, -1));

        pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeActionPerformed(evt);
            }
        });
        jPanel1.add(pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 260, -1));

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 260, -1));

        title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "Dr.", "Miss.", "Sir." }));
        title.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                titleItemStateChanged(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019" }));
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        lastNamehindi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNamehindiActionPerformed(evt);
            }
        });
        jPanel1.add(lastNamehindi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 260, -1));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 260, -1));

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 260, -1));

        numberoflivessaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberoflivessavedActionPerformed(evt);
            }
        });
        jPanel1.add(numberoflivessaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 260, -1));

        address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address2ActionPerformed(evt);
            }
        });
        jPanel1.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 260, -1));

        bankCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankCodeActionPerformed(evt);
            }
        });
        jPanel1.add(bankCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 260, -1));

        recommendingAuthorityothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendingAuthorityothersActionPerformed(evt);
            }
        });
        jPanel1.add(recommendingAuthorityothers, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 260, -1));

        posthumousY.setBackground(new java.awt.Color(255, 255, 255));
        mygroup2.add(posthumousY);
        posthumousY.setText("Yes");
        posthumousY.setFocusable(false);
        posthumousY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posthumousYActionPerformed(evt);
            }
        });
        jPanel1.add(posthumousY, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        posthumousN.setBackground(new java.awt.Color(255, 255, 255));
        mygroup2.add(posthumousN);
        posthumousN.setText("No");
        posthumousN.setFocusable(false);
        jPanel1.add(posthumousN, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        state.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateItemStateChanged(evt);
            }
        });
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 260, -1));

        earlierAwarded.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        earlierAwarded.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                earlierAwardedItemStateChanged(evt);
            }
        });
        jPanel1.add(earlierAwarded, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        jointDeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jointDeed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jointDeedItemStateChanged(evt);
            }
        });
        jPanel1.add(jointDeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        jLabel33.setText("*Please enter citation description upto 250 words");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

        jLabel35.setText("*Special characters like ^ [ ^ {}  , $ % & ] are not allowed ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 700, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setText("Citation :");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, -1, -1));
        jPanel1.add(citation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 590, 180));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("Upload Certificate * :");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, -1, -1));

        jButton1.setText("Choose file");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 960, -1, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1030, -1, -1));

        logOut.setText("LOGOUT");
        jPanel1.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1030, -1, -1));

        save.setText("SAVE");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveMouseReleased(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1030, -1, -1));

        awardAppliedfor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(awardAppliedfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        recommendingAuthority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        recommendingAuthority.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                recommendingAuthorityItemStateChanged(evt);
            }
        });
        jPanel1.add(recommendingAuthority, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        city.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityItemStateChanged(evt);
            }
        });
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 260, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sexMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexMActionPerformed

    private void firstNamehindiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNamehindiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNamehindiActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void DOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOIActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void address3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address3ActionPerformed

    private void districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtActionPerformed

    private void pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodeActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void lastNamehindiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNamehindiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNamehindiActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void numberoflivessavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberoflivessavedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberoflivessavedActionPerformed

    private void address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address2ActionPerformed

    private void bankCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankCodeActionPerformed

    private void recommendingAuthorityothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendingAuthorityothersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendingAuthorityothersActionPerformed

    private void posthumousYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posthumousYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posthumousYActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void saveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseReleased
        // TODO add your handling code here:
        submitForm();
    }//GEN-LAST:event_saveMouseReleased

    private void titleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_titleItemStateChanged
        // TODO add your handling code here:
        tte =(String) (title.getSelectedItem());
    }//GEN-LAST:event_titleItemStateChanged

    private void recommendingAuthorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_recommendingAuthorityItemStateChanged
        // TODO add your handling code here:
        ra = (String) recommendingAuthority.getSelectedItem();
    }//GEN-LAST:event_recommendingAuthorityItemStateChanged

    private void jointDeedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jointDeedItemStateChanged
        // TODO add your handling code here:
        jd = (String) jointDeed.getSelectedItem();
    }//GEN-LAST:event_jointDeedItemStateChanged

    private void earlierAwardedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_earlierAwardedItemStateChanged
        // TODO add your handling code here:
        ea =(String) earlierAwarded.getSelectedItem();
    }//GEN-LAST:event_earlierAwardedItemStateChanged

    private void stateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateItemStateChanged
        // TODO add your handling code here:
       
        stt = (String)state.getSelectedItem();
        stateCode = state.getSelectedIndex();
        for(int i = 0; i <= cy.get(stateCode).size();i++){
           city.addItem(cy.get(stateCode).get(i));
        }
    }//GEN-LAST:event_stateItemStateChanged

    private void cityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityItemStateChanged
        // TODO add your handling code here:
        cty = (String) city.getSelectedItem();
    }//GEN-LAST:event_cityItemStateChanged

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        // TODO add your handling code here:
        yr = Integer.parseInt( (String)(year.getSelectedItem()));
//        yr = 2019;
    }//GEN-LAST:event_yearItemStateChanged

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseReleased
    public void submitForm(){
        fn = firstName.getText();
        ln = lastName.getText();
        rao = recommendingAuthorityothers.getText();
        gen = sexM.isSelected() == true ? "Male" : "Female";
        dob = DOB.getText();
        doi = DOI.getText();
        add1 = address1.getText();
        add2 = address2.getText();
        add3 = address3.getText();
        dist = district.getText();
        pc = Integer.parseInt(pincode.getText());
//        pc = 32323;
        ph = Long.parseLong(phone.getText());
//        ph = 23232;
        posth = posthumousN.isSelected() == true ? "Yes" : "No";
        ag = Integer.parseInt(age.getText());
//        ag =43;
        nols = Integer.parseInt(numberoflivessaved.getText());
//        nols = 2;
        bb = bankCode.getText();
        cit = citation.getText();
        try{
        Statement st = cn.createStatement();
        String name = "py";
        int id = 222;
        String gy;
        
        if(modifyIs == false){
            gy = "insert into `report` values ('"+tte+"',"+yr+",'"+fn+"','"+ln+"','"+ra+"','"+apf+"','"+rao+"',"+ph+",'"+gen+"','"+posth+"','"+dob+"',"+ag+",'"+doi+"',"+nols+",'"+add1+"','"+add2+"','"+add3+"','"+cty+"','"+dist+"','"+stt+"',"+pc+",'"+bb+"','"+jd+"','"+ea+"','"+cit+"',"+1+")";
            st.execute(gy);
        }else{
            try{
            String my = "update `report` set Title = '"+tte+"',Year = "+yr+" where FirstName = '"+pkName+"' and LastName = '"+pklast+"' and DOB ='"+pkdob+"'";                           ;
            st.execute(my);
            }catch(Exception e){
                System.out.println("CAnnot modify" + e);
            }
            }
        }catch(Exception e){
          System.out.println(e);  
        }
    }
    public String tte,fn,ln,ra,apf,rao,gen,posth,dob,doi,add1,add2,add3,cty,dist,stt,bb,jd,ea,cit;
    int ag,nols,pc,stateCode,yr;
    long ph;
    public void setValue(){
        try{
         
         int lvl = 1;
         Statement st = cn.createStatement();
         String py = "select * from report where Year = " + Year + " and  RA = '" + Ra+"' and APF = '" +Aaf+"'";
         getData = st.executeQuery(py);
        while(getData.next()){
        System.out.println(lvl + " --> " +getData.getString(3));
        if(lvl == sid){
           pkName = getData.getString(3);
           pklast = getData.getString(4);
           pkdob = getData.getString(11);
          firstName.setText(getData.getString(3));
          lastName.setText(getData.getString(4));
          recommendingAuthorityothers.setText(getData.getString(7));
        phone.setText((getData.getInt(8)) + "");
        DOB.setText(getData.getString(11));
        age.setText(getData.getInt(12) + "");
        DOI.setText(getData.getString(13));
        numberoflivessaved.setText(getData.getInt(14)+"");
        address1.setText(getData.getString(15));
        address2.setText(getData.getString(16));
        address3.setText(getData.getString(17));
        district.setText(getData.getString(19));
        pincode.setText(getData.getInt(21)+"");
        bankCode.setText(getData.getString(22));
        citation.setText(getData.getString(25));
//        for(int i = 0 ;i<title.getItemCount();i++){
//            if((String)title.getItemAt(i)==getData.getString(1)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<year.getItemCount();i++){
//            if(Integer.parseInt(title.getItemAt(i))==getData.getInt(2)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<recommendingAuthority.getItemCount();i++){
//            if((String)recommendingAuthority.getItemAt(i)==getData.getString(5)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<awardAppliedfor.getItemCount();i++){
//            if((String)awardAppliedfor.getItemAt(i)==getData.getString(6)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<city.getItemCount();i++){
//            if((String)city.getItemAt(i)==getData.getString(18)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<state.getItemCount();i++){
//            if((String)state.getItemAt(i)==getData.getString(20)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//
//        for(int i = 0 ;i<jointDeed.getItemCount();i++){
//            if((String)jointDeed.getItemAt(i)==getData.getString(23)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
//        for(int i = 0 ;i<earlierAwarded.getItemCount();i++){
//            if((String)earlierAwarded.getItemAt(i)==getData.getString(24)){
//                title.setSelectedIndex(i);
//                break;
//            }
//        }
        break;
        }
        lvl++;
        }
        
        }catch(Exception e){
            System.err.println(e);
        }
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField DOI;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JTextField address3;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> awardAppliedfor;
    private javax.swing.JButton back;
    private javax.swing.JTextField bankCode;
    private javax.swing.JTextField citation;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JTextField district;
    private javax.swing.JComboBox<String> earlierAwarded;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField firstNamehindi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jointDeed;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lastNamehindi;
    private javax.swing.JButton logOut;
    private javax.swing.ButtonGroup mygroup1;
    private javax.swing.ButtonGroup mygroup2;
    private javax.swing.JTextField numberoflivessaved;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pincode;
    private javax.swing.JRadioButton posthumousN;
    private javax.swing.JRadioButton posthumousY;
    private javax.swing.JComboBox<String> recommendingAuthority;
    private javax.swing.JTextField recommendingAuthorityothers;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton sexF;
    private javax.swing.JRadioButton sexM;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JComboBox<String> title;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
