/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nic;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JTable;
import static nic.Nic.cn;
import static nic.loginScreen.admin_id;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author priyansh singh
 */
public class modify extends javax.swing.JFrame {
    public static int Year;
    public static ResultSet getData;
    public static boolean modifyIs = false;
    public static String Ra;
    public static int sid=0;
    public static String Aaf;
    /**
     * Creates new form modify
     */
    public modify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        ra = new javax.swing.JComboBox<>();
        aaf = new javax.swing.JComboBox<>();
        gb = new javax.swing.JButton();
        lo = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        searchResult = new javax.swing.JComboBox<>();
        modify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("JEEVAN RAKSHA PADAK SERIES ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("PERSONAL PROFILE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("YEAR :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("RECOMMENDING AUTHORITY :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("AWARD APPLIED FOR :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        year.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019" }));
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 290, -1));

        ra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 2" }));
        ra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                raItemStateChanged(evt);
            }
        });
        jPanel1.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 290, -1));

        aaf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        aaf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aafItemStateChanged(evt);
            }
        });
        jPanel1.add(aaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        gb.setText("GO BACK");
        jPanel1.add(gb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        lo.setText("LOGOUT");
        jPanel1.add(lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        search.setText("SEARCH");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchMouseReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("SELECT PERSON : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        searchResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        searchResult.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchResultItemStateChanged(evt);
            }
        });
        jPanel1.add(searchResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 412, 300, 30));

        modify.setText("Modify");
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modifyMouseReleased(evt);
            }
        });
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jPanel1.add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        // TODO add your handling code here:
        Year = Integer.parseInt((String)year.getSelectedItem());
    }//GEN-LAST:event_yearItemStateChanged

    private void raItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_raItemStateChanged
        // TODO add your handling code here:
        Ra = (String) ra.getSelectedItem();
    }//GEN-LAST:event_raItemStateChanged

    private void aafItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aafItemStateChanged
        // TODO add your handling code here:
        Aaf = (String) aaf.getSelectedItem();
    }//GEN-LAST:event_aafItemStateChanged

    private void searchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseReleased
        // TODO add your handling code here:
        searchResult.removeAllItems();
        searchResult.addItem("Select");
        try {
            Statement rs = cn.createStatement();
            Ra = "Item 2";
            Aaf = "null";
            String eq = "select * from report where Year = " + Year + " and  RA = '" + Ra+"' and APF = '" +Aaf+"'";
            getData = rs.executeQuery(eq);
            
            while(getData.next()){
                String s = "First Name :"+getData.getString(3) +"          Last Name : " + getData.getString(4) + "          DOB : " +getData.getString(11);
                searchResult.addItem(s);
            }
           
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_searchMouseReleased

    private void searchResultItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchResultItemStateChanged
        // TODO add your handling code here:
     
        sid = searchResult.getSelectedIndex();
    }//GEN-LAST:event_searchResultItemStateChanged

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void modifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyMouseReleased
        // TODO add your handling code here:
         modifyIs = true;
      new entryForm().setVisible(true);

    }//GEN-LAST:event_modifyMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify().setVisible(true);
            }
        });
    }
    
    
    public void modifyR(){
        
    }
    
    
    private javax.swing.JScrollPane tp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aaf;
    private javax.swing.JButton gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lo;
    private javax.swing.JButton modify;
    private javax.swing.JComboBox<String> ra;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> searchResult;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
