/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nic;

/**
 *
 * @author priyansh singh
 */
public class userScreen extends javax.swing.JFrame {

    /**
     * Creates new form userScreen
     */
    public userScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        entryForm = new javax.swing.JButton();
        editRecord = new javax.swing.JButton();
        View = new javax.swing.JButton();
        citationReport = new javax.swing.JButton();
        Password = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\img\\logo1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 400, 860));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 403, 680));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryForm.setBackground(new java.awt.Color(255, 255, 255));
        entryForm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        entryForm.setText("1. Entry Form");
        entryForm.setContentAreaFilled(false);
        entryForm.setFocusable(false);
        entryForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryFormActionPerformed(evt);
            }
        });
        jPanel3.add(entryForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, 30));

        editRecord.setBackground(new java.awt.Color(255, 255, 255));
        editRecord.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        editRecord.setText("2. Edit/Modify Record");
        editRecord.setContentAreaFilled(false);
        editRecord.setFocusable(false);
        editRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRecordActionPerformed(evt);
            }
        });
        jPanel3.add(editRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        View.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        View.setText("3. View/Print");
        View.setContentAreaFilled(false);
        View.setFocusable(false);
        jPanel3.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        citationReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        citationReport.setText("4. JRP Awards Citation Report");
        citationReport.setContentAreaFilled(false);
        citationReport.setFocusable(false);
        citationReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                citationReportMouseReleased(evt);
            }
        });
        citationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citationReportActionPerformed(evt);
            }
        });
        jPanel3.add(citationReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        Password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password.setText("5.Change Password");
        Password.setContentAreaFilled(false);
        Password.setFocusable(false);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel3.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        logOut.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOut.setText("6.Log Out");
        logOut.setContentAreaFilled(false);
        logOut.setFocusable(false);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel3.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\img\\flag1.jpg")); // NOI18N
        jLabel3.setText("MENU");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 680));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 630, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void citationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citationReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citationReportActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
      new logout().setVisible(true);
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logOutActionPerformed

    private void entryFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryFormActionPerformed
new entryForm().setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_entryFormActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
new changepassword().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void editRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRecordActionPerformed
new modify().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_editRecordActionPerformed

    private void citationReportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citationReportMouseReleased
        // TODO add your handling code here:
        new citationReport().setVisible(true);
    }//GEN-LAST:event_citationReportMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Password;
    private javax.swing.JButton View;
    private javax.swing.JButton citationReport;
    private javax.swing.JButton editRecord;
    private javax.swing.JButton entryForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOut;
    // End of variables declaration//GEN-END:variables
}
